### ISSUE TITLE
Cannot find the module

### ISSUE THREAD

**Issue by spawn004** [microsoft/omnichannel-chat-widget#156]
Tried to implement widget as in example (first I've tried with dummy config as in example and then with "real" config) and got the issue "Cannot find module './components/header/Header'" as a result.

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/17340955/199543119-80c259ef-73f2-4101-84e1-14398506c67c.png">

**Comment by sarojkpr** [comment]
Hi, thanks for reporting the issue. Are you using JS sample or Typescript?

**Comment by spawn004** [comment]
Hello! Thank you for reaching out to me. TypeScript sample? I’ve found only
JavaScript sample in the documentation, with outdated syntax, so I needed
to wrap evething in hook “useEffect”. I did something wrong?

Сб, 5 нояб. 2022 г. в 03:15, sarojkpr ***@***.***>:

**Comment by charliewang95** [comment]
Hi if possible can you please share a repo for us to investigate?
