### ISSUE TITLE
Unable to initialize the chat widget

### ISSUE THREAD

**Issue by nithyasam** [microsoft/omnichannel-chat-widget#16]
When setting up the widget as described in the Basic example section, I'm running into the following issue. It appears that some component file is missing in the library.

* From dev console
`Uncaught Error: Cannot find module './components/header/Header'
    at webpackMissingModule (ReactRefreshEntry.js:23:1)
    at Module../node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js (ReactRefreshEntry.js:23:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Module../node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js (index.js:18:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Module../src/index.js (App.js:27:1)`

* From compile log
`Compiled with problems:X

ERROR in ./src/index.js 55:40-54

export 'default' (imported as 'LiveChatWidget') was not found in '@microsoft/omnichannel-chat-widget' (possible exports: BroadcastService, decodeComponentString, encodeComponentString)

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 1:0-63

Module not found: Error: Can't resolve './components/header/Header' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'Header.js'?
BREAKING CHANGE: The request './components/header/Header' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 2:0-63

Module not found: Error: Can't resolve './components/footer/Footer' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'Footer.js'?
BREAKING CHANGE: The request './components/footer/Footer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 3:0-93

Module not found: Error: Can't resolve './components/confirmationpane/ConfirmationPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'ConfirmationPane.js'?
BREAKING CHANGE: The request './components/confirmationpane/ConfirmationPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 4:0-75

Module not found: Error: Can't resolve './components/chatbutton/ChatButton' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'ChatButton.js'?
BREAKING CHANGE: The request './components/chatbutton/ChatButton' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 5:0-102

Module not found: Error: Can't resolve './components/inputvalidationpane/InputValidationPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'InputValidationPane.js'?
BREAKING CHANGE: The request './components/inputvalidationpane/InputValidationPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 6:0-96

Module not found: Error: Can't resolve './components/proactivechatpane/ProactiveChatPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'ProactiveChatPane.js'?
BREAKING CHANGE: The request './components/proactivechatpane/ProactiveChatPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 7:0-96

Module not found: Error: Can't resolve './components/reconnectchatpane/ReconnectChatPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'ReconnectChatPane.js'?
BREAKING CHANGE: The request './components/reconnectchatpane/ReconnectChatPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 8:0-78

Module not found: Error: Can't resolve './components/loadingpane/LoadingPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'LoadingPane.js'?
BREAKING CHANGE: The request './components/loadingpane/LoadingPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 9:0-93

Module not found: Error: Can't resolve './components/outofofficehourspane/OOOHPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'OOOHPane.js'?
BREAKING CHANGE: The request './components/outofofficehourspane/OOOHPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 10:0-96

Module not found: Error: Can't resolve './components/prechatsurveypane/PreChatSurveyPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'PreChatSurveyPane.js'?
BREAKING CHANGE: The request './components/prechatsurveypane/PreChatSurveyPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 11:0-99

Module not found: Error: Can't resolve './components/postchatsurveypane/PostChatSurveyPane' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'PostChatSurveyPane.js'?
BREAKING CHANGE: The request './components/postchatsurveypane/PostChatSurveyPane' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 12:0-71

Module not found: Error: Can't resolve './common/encodeComponentString' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'encodeComponentString.js'?
BREAKING CHANGE: The request './common/encodeComponentString' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 13:0-71

Module not found: Error: Can't resolve './common/decodeComponentString' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'decodeComponentString.js'?
BREAKING CHANGE: The request './common/decodeComponentString' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 14:0-63

Module not found: Error: Can't resolve './services/BroadcastService' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'BroadcastService.js'?
BREAKING CHANGE: The request './services/BroadcastService' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 15:0-49

Module not found: Error: Can't resolve './common/Constants' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'Constants.js'?
BREAKING CHANGE: The request './common/Constants' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 16:0-93

Module not found: Error: Can't resolve './components/callingcontainer/CallingContainer' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'CallingContainer.js'?
BREAKING CHANGE: The request './components/callingcontainer/CallingContainer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 17:0-109

Module not found: Error: Can't resolve './components/callingcontainer/subcomponents/CurrentCall/CurrentCall' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'CurrentCall.js'?
BREAKING CHANGE: The request './components/callingcontainer/subcomponents/CurrentCall/CurrentCall' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 18:0-112

Module not found: Error: Can't resolve './components/callingcontainer/subcomponents/IncomingCall/IncomingCall' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'IncomingCall.js'?
BREAKING CHANGE: The request './components/callingcontainer/subcomponents/IncomingCall/IncomingCall' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-components/lib/esm/index.js 19:0-91

Module not found: Error: Can't resolve './components/callingcontainer/subcomponents/Timer/Timer' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-components/lib/esm'
Did you mean 'Timer.js'?
BREAKING CHANGE: The request './components/callingcontainer/subcomponents/Timer/Timer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 2:0-62

Module not found: Error: Can't resolve './hooks/useChatContextStore' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-widget/lib/esm'
Did you mean 'useChatContextStore.js'?
BREAKING CHANGE: The request './hooks/useChatContextStore' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 3:0-54

Module not found: Error: Can't resolve './hooks/useChatSDKStore' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-widget/lib/esm'
Did you mean 'useChatSDKStore.js'?
BREAKING CHANGE: The request './hooks/useChatSDKStore' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 4:0-87

Module not found: Error: Can't resolve './components/livechatwidget/LiveChatWidget' in '/Learn/custom-chat-widget/node_modules/@microsoft/omnichannel-chat-widget/lib/esm'
Did you mean 'LiveChatWidget.js'?
BREAKING CHANGE: The request './components/livechatwidget/LiveChatWidget' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 5:0-112

export 'encodeComponentString' (reexported as 'encodeComponentString') was not found in '@microsoft/omnichannel-chat-components' (module has no exports)

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 5:0-112

export 'decodeComponentString' (reexported as 'decodeComponentString') was not found in '@microsoft/omnichannel-chat-components' (module has no exports)

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 5:0-112

export 'BroadcastService' (reexported as 'BroadcastService') was not found in '@microsoft/omnichannel-chat-components' (module has no exports)`

**Comment by xTEddie** [comment]
@nithyasam How is the package being used? Is it using `create-react-app`?

**Comment by nithyasam** [comment]
Yes, i used create-react-app to setup the base react app.

**Comment by xTEddie** [comment]
@nithyasam Please try the following steps:

1. Update `react-scripts` version to `4.0.3` in `package.json`
2. Update `browserlist` in `package.json` with 
```diff
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
-      ">0.2%",
-      "not dead",
-      "not op_mini all"
+      ">0.2%",
+      "not dead",
+      "not op_mini all"
    ]
  }
```
3. Delete `/node_modules`
4. Reinstall all the packages via `yarn install`
5. Start the app via `yarn start`

Let me know if this fixes the issue.

**Comment by nithyasam** [comment]
The above changes fixed the issue. Thank you!
