### ISSUE TITLE
Multiple chat widget in Same browser

### ISSUE THREAD

**Issue by ss-kumar** [microsoft/omnichannel-chat-widget#162]
@sarojkpr 
Is it possible to have multiple chat widget in same browser? We tried to render multiple widgets in same browser but looks like because of Context both instances started sharing same conversation and messages as shown in below screenshot. Please let us know if there is any work around to achieve this use case.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/114021495/201926978-f095c085-baab-4b98-bc98-6773e07c8f1d.png">

Initially there was an issue in omnichannel-chat-sdk to load multiple instances in the widget which got resolved as part of enhancement  in below ticket
https://github.com/microsoft/omnichannel-chat-sdk/issues/145

**Comment by sarojkpr** [comment]
Is it possible to share the controlProps difference between both widgets? (https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/livechatwidget/interfaces/ILiveChatWidgetProps.ts#:~:text=%3F%3A%20IConfirmationPaneStatefulProps%3B-,controlProps,-%3F%3A%20ILiveChatWidgetControlProps%3B)

**Comment by lowcodelewis** [comment]
@charliewang95 and others, would anyone have any idea on how to achieve the requirement of having multiple chat widgets in the same browser. 

We are attempting to build a consult experience that allows for conversation routing and other features and so need to utilise the existing chat for this. To achieve this we are creating a side pane in Dynamics from the agent experience and then surfacing a chat widget which will push the conversation through to an internal service line based on a selected department in the pre conversation survey.

The problem I have is imagine an agent works on three conversations and has to consult for all 3 i.e. needs 3 sidebars each which should have a unique chat widget to start 3 separate unique conversations... this does not work as the conversations in all 3 sidebars just sync ;(

Apologies, I am a little at the beginning of my dev pathway and primarily work with Low Code and Biz Apps. If anyone could provide a simple guide or push in the right direction of how to achieve this requirement with HTML, JS and web resources in Dynamics that would be amazing!

Thank you so much in advance!

Lewis Baybutt
BizApps MVP - @lowcodelewis

**Comment by charliewang95** [comment]
The `widgetInstanceId` approach above (Adding unique `widgetInstanceId` into `controlProps` for each different tab) would support multiple chat instances in the same browser, but across different tabs. Currently there's no good way to put multiple chats into the same tab. Have you tried putting them in separate iframes and render LCW inside each iframe?

**Comment by lowcodelewis** [comment]
Thanks Charlie. To change the `widgetInstanceId` in the `controlProps` for each chat widget could I do this with the out the box  LCW and the data-customization-callback? Or do I have to develop a custom chat widget here to do this? Is there any step by step type guidance on that anywhere? Thanks so much in advance

**Comment by lowcodelewis** [comment]
Sorry @charliewang95 please ignore the comment above. I've used the SDK and components to create a chat widget which is working in Dynamics, having multiple separated widgets in separate side bars. Thanks :) 👍
