### ISSUE TITLE
How to send custom contexts to Omnichannel/PVA?

### ISSUE THREAD

**Issue by Thbpdev** [microsoft/omnichannel-chat-widget#219]
Hello @abhinab22mohanty, @sarojkpr, I'm struggling to send custom contexts with the JavaScript sample widget. I tried to use the snippet that worked with the OOTB lcw widget provided here: https://learn.microsoft.com/en-us/dynamics365/customer-service/send-context-starting-chat?source=recommendations but it seems to not work when I put in the test.html file.

Could you help me make it work please? Do I need to use a different code, can you give me an example of integration with the JavaScript sample please?

Thanks a lot for your help!

Best regards.

**Comment by charliewang95** [comment]
Hello,

The link you shared is the SDK method for our out-of-box offering, not this open source widget. 

To send context using the chat-widget itself, you need to post a "SetCustomContext" BroadcastEvent from the widget consumer before starting the chat. See this document https://github.com/microsoft/omnichannel-chat-widget/blob/main/docs/Telemetry.md#:~:text=BroadcastService.postMessage(onClickEvent)%3B

**Comment by Thbpdev** [comment]
Hello @charliewang95,

Thanks a lot for your answer, I tried to put the sample code you gave me at several places but I'm not able to make it work. 

Sorry, I'm new to this but I'm not sure where to put it when using the JavaScript sample widget?

Could you give me a more explicit sample/explanation please? What do you mean by the widget consumer before starting the chat?

Thanks a lot for your help!

Best regards.

**Comment by ferodom** [comment]
having the same issue

**Comment by arnavsimer** [comment]
at which place we should call . I tried using the below code in webpack 5 example code but i am getting BroadcastService as null. So i added the call to `postMessage ` function in setTimeout. I can see that set context event triggered in the console logs but i don't see its value set in the copilot studio 

```
const setCustomContextEvent = {
        eventName: "SetCustomContext",
        payload: {} //the context object
    };
BroadcastService.postMessage(setCustomContextEvent);
```
