### ISSUE TITLE
What's the right way to customize the rendering of Adaptive Cards

### ISSUE THREAD

**Issue by Thbpdev** [microsoft/omnichannel-chat-widget#244]
Hi @charliewang95, @abhinab22mohanty, @sarojkpr, @xTEddie,

I wonder what's the right way to customize the Adaptive Cards design like the font, the border-radius, color, etc. of all the elements of a rendered Adaptive Cards please?

With the defaultProps, I can see there's just a way to change the background and color: https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/livechatwidget/common/defaultProps/dummyDefaultProps.ts

`adaptiveCardStyles: {
            background: "white",
            color: "black"
        }`
 
 Thanks a lot for your help!
 
 Best regards.

**Comment by charliewang95** [comment]
Can you please elaborate which scenario you're using the adaptive cards?

If you're using PVA bot with AdaptiveCards, then it can only be modified from PVA side.

**Comment by Thbpdev** [comment]
@charliewang95 yes I'm using a PVA bot and sending an Adaptive Card via Bot Framework Composer.

I would like for example to be able to change the color (to red) and border-radius (to 8px) of the element button **class="ac-pushButton style-default ac-selectable"** of the rendered adaptive card in the LCW. By default it's blue and the button has sharp edges.

**From this:**
![image](https://user-images.githubusercontent.com/127031713/231112255-af1e5e42-1156-4aab-898d-aeb70a02e39b.png)

**To this:** 
![image](https://user-images.githubusercontent.com/127031713/231113495-21166bf1-7765-41bb-b25c-d5c17d8c126f.png)

Per my understanding it's the host app that is controlling the way an Adaptive Card should look like. For instance, on Teams the buttons will have the same design as the default one of Teams. https://learn.microsoft.com/en-us/adaptive-cards/rendering-cards/getting-started

How would you do that from PVA side then? Thanks a lot for your help and answer!

**Comment by Thbpdev** [comment]
@charliewang95 or is there a way to pass a HostConfig to adapt the design of the Adaptive Cards inside bot messages? Thanks!

**Comment by charliewang95** [comment]
Webchat's AdaptiveCardsHostConfig is exposed in PR #297. More css can be customized through this prop https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/webchatcontainerstateful/interfaces/IWebChatContainerStatefulProps.ts#L24
