### ISSUE TITLE
Not able to activate the bot typing indicators

### ISSUE THREAD

**Issue by Thbpdev** [microsoft/omnichannel-chat-widget#245]
Hi @charliewang95, @abhinab22mohanty, @sarojkpr, @xTEddie,

I've seen several parameters related to the typing indicators in the defaultProps but I'm not able to find the right one to activate this possibility for the bot. https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/livechatwidget/common/defaultProps/dummyDefaultProps.ts

What are the settings I need to put to have the same behaviour you have in your screenshot below, 3 dots waving and text Bot is typing...? Do I need to activate or deactivate a specific middleware? Can you share me a working config to have the indicators please?

https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/livechatwidget/__screenshots__/stateful-components-live-chat-widget-live-chat-widget-fixed-size-cancel-close-chat-chromium-snap.png

Thanks a lot for your help!

Best regard.

**Comment by charliewang95** [comment]
Omnichannel Bots (PVA/BYOB) today do not support typings. When bot is trying to respond no typing message is sent over. This is currently by design.

If needed please reach out to Omnichannel PMs for a feature request

**Comment by ritwickbhargav80** [comment]
Hi @charliewang95,

We're interested in this feature. Has it become available in the latest release?
