### ISSUE TITLE
Live chat widget 2.0 loading widget.js over network - heavy first load for website

### ISSUE THREAD

**Issue by ajj10** [microsoft/omnichannel-chat-widget#284]
**Describe the bug**
When using the Live chat widget 2.0 or v2 script, the widget.js file is transferred over network resulting in a very slow and heavy load.
Is this expected behavior for the v2 script? 

**To Reproduce**
1. Load v2 script onto html website and see under network tab

**Expected behavior**
I would assume the expected behavior to be similar to the v1 script where no heavy js files are transferred over the network resulting in a very slow and heavy load of the website.

**Screenshots**
v1 script loading
![image](https://github.com/microsoft/omnichannel-chat-widget/assets/37146798/e10ef45c-6684-4b1c-a3e9-2bc8bace5303)
v2 script loading
![image](https://github.com/microsoft/omnichannel-chat-widget/assets/37146798/7707e3ad-1353-4cb3-90c1-b11ec6c2e9f2)

**Comment by charliewang95** [comment]
This is an issue with the OOB widget (bundling layer), not with this React component. Please create a support ticket/IcM to track
