### ISSUE TITLE
Correct Link for IRawStylebase

### ISSUE THREAD

**Issue by ferodom** [microsoft/omnichannel-chat-widget#286]
**Describe the bug**
The link on the documentation for ISawStyleBase goes to a 404 

**To Reproduce**
1. Go to https://github.com/microsoft/omnichannel-chat-widget/tree/main#stateless-ui-components
2. Scroll down to the end of the table
3. Click the link
[IRawStyleBase](https://docs.microsoft.com/en-us/javascript/api/merge-styles/irawstylebase?view=office-ui-fabric-react-latest) 5. 
Link is worng

**Expected behavior**
Link goes to the documentation for Irawstylebase

**Comment by charliewang95** [comment]
Fixed in #373
