### ISSUE TITLE
 error : Can't resolve 'react-native'

### ISSUE THREAD

**Issue by adtakle** [microsoft/omnichannel-chat-widget#313]
**Describe the bug**
Getting a build error when trying to build my changes:
Module not found : error : Can't resolve 'react-native' in 'C:\repos\SupportExtension\src\SupportExtension\Client\React\node_modules\@microsoft\omnichannel-chat-sdk\lib\telemetry' [C:\repos\SupportExtension\src\SupportExtension\SupportExtension.csproj]

There's no dependency on `react-native` when I run `npm list react-native`:
![image](https://github.com/microsoft/omnichannel-chat-widget/assets/69855282/9fd25be6-468e-4fac-a992-1f61be5069f7)

It also looks like any references to `react-native` are `optional` in the package-lock.json, so not sure why I'm getting this error.

I see here that `react-native` should be optional, but the error above is an error, not a warning: [#178](https://github.com/microsoft/omnichannel-chat-sdk/issues/178)

I'm using versions the following package versions:
    "@microsoft/omnichannel-chat-sdk": "1.3.0",
    "@microsoft/omnichannel-chat-widget": "1.0.5-main.b771061",

I can share links to our source code privately if needed.

**Comment by koreykiran** [comment]
Adding a fallback by setting the react-native to false did the trick. 

`reactViewBuild.addFallbacks({
    "react-native": false
});`
