### ISSUE TITLE
Can't start or build the typescript example

### ISSUE THREAD

**Issue by MathieuNadeauHilo** [microsoft/omnichannel-chat-widget#360]
When trying to run the typescript example, i'm getting errors and can't build or start the project in localhost.

tried the webpack5 example too, and it's not working either. Am I missing something in the installation process?
![image](https://github.com/microsoft/omnichannel-chat-widget/assets/146737823/6bd5f124-47d0-4419-8ac7-fff646522e81)

**Comment by MathieuNadeauHilo** [comment]
Also tried without touching anything and just running the yarn build, and I get a few errors concerning react native. 
![image](https://github.com/microsoft/omnichannel-chat-widget/assets/146737823/0f6afc7b-d861-4056-b1c2-fdacc79d266b)

**Comment by lowcodelewis** [comment]
Hey there @MathieuNadeauHilo 

To resolve this, you can include the following object in your webpack.config.js file.

`
 externals: {
        "react-native": true
    }
`

Thanks! :)
