### ISSUE TITLE
Header div element is being displayed on loading pane

### ISSUE THREAD

**Issue by elishuwon-mitchell** [microsoft/omnichannel-chat-widget#389]
**Describe the bug**
The header div element is displayed on the loading pane with whatever style props is defined in the headerProps config. This is causing conflicting styling issues because we are passing a custom loading pane element as an override and this div being displayed is above it. Even when hideLoadingPane is set the true, this div element is still being displayed.

**To Reproduce**
1. Used the following link: https://microsoft.github.io/omnichannel-chat-widget/docs/storybook/?path=/story/stateful-components-live-chat-widget--default&globals=outline:true;backgrounds.grid:false

2. To better display the issue, update the background color in the headerProps.styleProps.generalStyleProps.background to be "red" for example

3. Load the widget

**Expected behavior**
The header div element should not be displayed on the loading pane.

**Screenshots**
Updated the background color in the header props to better display the issue:
<img width="625" alt="image" src="https://github.com/microsoft/omnichannel-chat-widget/assets/14806004/052353ab-521f-4d99-831e-cf9f6ac73f74">

Header div element is being displayed on the loading pane with the config defined in the header props:

<img width="364" alt="image" src="https://github.com/microsoft/omnichannel-chat-widget/assets/14806004/2a12cdd8-d400-46aa-95a4-91e8a30bd67e">

Even when `hideLoadingPane` is set to true this header div element is still being displayed:
<img width="1048" alt="image" src="https://github.com/microsoft/omnichannel-chat-widget/assets/14806004/a4473ad4-4240-4741-b438-87796f4aa6cf">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here. A link to reproduce the issue or a repo that contains the repro is much appreciated.

**Comment by charliewang95** [comment]
Header cannot be hidden only for loading pane, as there must be a way to minimize the widget, otherwise it will block website content. Also we cannot afford to allow customization of header for each single pane. So the current behavior is by design
