### ISSUE TITLE
Reconnect pane still displays when controlProps.hideReconnectPane is set to true

### ISSUE THREAD

**Issue by elishuwon-mitchell** [microsoft/omnichannel-chat-widget#401]
**Describe the bug**
The reconnect pane is still displayed despite the `controlProps.hideReconnectPane` field being set to true.

<img width="215" alt="image" src="https://github.com/microsoft/omnichannel-chat-widget/assets/14806004/cb86c271-e82d-4bb4-b145-ccff9db621e5">

**To Reproduce**
1. Set `controlProps.hideeReconnectPane` to `true`
2. Initiate a reconnect chat
3. The reconnect pane is displayed

**Expected behavior**
The reconnect pane should not be displayed when that field is set to true.

**Screenshots**
<img width="1054" alt="image" src="https://github.com/microsoft/omnichannel-chat-widget/assets/14806004/2f773922-4bec-41b2-ab22-a6d03318722a">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here. A link to reproduce the issue or a repo that contains the repro is much appreciated.

**Comment by charliewang95** [comment]
Created bug in ADO to track, will sync updates in this thread as well. [Bug 3739363](https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/3739363): [LCW][V2] controlProps.hideReconnectPane is set to true is not hiding Reconnect Prompt

**Comment by elopezanaya** [comment]
Bug was closed as part of January sprint : PR -> https://github.com/microsoft/omnichannel-chat-widget/pull/423
