### ISSUE TITLE
Build issues after upgrading to latest package version

### ISSUE THREAD

**Issue by adtakle** [microsoft/omnichannel-chat-widget#43]
I am seeing the following errors after upgrading to the latest package version, and trying to build the project with Webpack. I was previously using version `"@microsoft/omnichannel-chat-widget": "0.1.0-main.89c6531"` and tried upgrading to version `"@microsoft/omnichannel-chat-widget": "0.1.0-main.47ede4d"`. Can you please take a look and help fix these build errors?

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/components/livechatwidget/common/registerTelemetryLoggers.js 4:0-102
Module not found: Error: Package path ./package.json is not exported from package C:\repos\AzRP\src\Services\Chat\Chat.Web\Client\LiveChat\node_modules\@microsoft\omnichannel-chat-components (see exports field in C:\repos\AzRP\src\Services\Chat\Chat.Web\Client\LiveChat\node_modules\@microsoft\omnichannel-chat-components\package.json)
@ ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/components/livechatwidget/livechatwidgetstateful/LiveChatWidgetStateful.js 40:0-78 72:4-28
@ ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/components/livechatwidget/LiveChatWidget.js 5:0-85 19:38-60
@ ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 4:0-87 4:0-87
@ ./src/liveChatWidget.tsx 33:0-68 121:111-125

ERROR in ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/components/livechatwidget/common/registerTelemetryLoggers.js 41:37-51
Can't import the named export 'version' (imported as 'chatSdkVersion') from default-exporting module (only default export is available)
@ ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/components/livechatwidget/livechatwidgetstateful/LiveChatWidgetStateful.js 40:0-78 72:4-28
@ ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/components/livechatwidget/LiveChatWidget.js 5:0-85 19:38-60
@ ./node_modules/@microsoft/omnichannel-chat-widget/lib/esm/index.js 4:0-87 4:0-87

**Comment by sarojkpr** [comment]
This has been fixed with latest version, you would also need to include `chatSdkVersion` and other version numbers in `import`. Please refer the readme.md for details.
