### ISSUE TITLE
node-fetch vulnerability causing build pipeline failure

### ISSUE THREAD

**Issue by dhruveshsheladiya** [microsoft/omnichannel-chat-widget#58]
Our ADO build pipeline is failing at the Component Governance step due to High severity vulnerability in the Node-Fetch version  2.6.1. Component governance shows the due date to resolve this npm package 2022-06-16T20:09:00.2569253Z  and since this deadline passed, build pipelines are failing and that stops us from deploying any changes related to the new LCW to staging or production.

node-fetch is being used by package @azure/core-http and @azure/core-http is being used by two different packages:

![image](https://user-images.githubusercontent.com/10868253/176703180-f0ee1e80-a2a7-4d64-87df-1afa7df074a6.png)

Component Governance error:

![image](https://user-images.githubusercontent.com/10868253/176703520-a7611095-7af3-4b7d-beb3-8efc9d26e3b6.png)

**Comment by charliewang95** [comment]
We also have an ADO pipeline but this hasn't popped up. @dhruveshsheladiya Could you share the CG alert link?

**Comment by sarojkpr** [comment]
This has been fixed after upgrading the node-fetch package version by running `npm update node-fetch`
