### ISSUE TITLE
Unable to update styling of system messages

### ISSUE THREAD

**Issue by elishuwon-mitchell** [microsoft/omnichannel-chat-widget#62]
There is no option to add/update styling for system messages displayed in the chat. This prevents the ability to update the text color of these messages to ensure consistency with Azure Portal across dark themes. An example of what the default text color for these messages against a dark theme can be seen below.

A similar ask is to be able to update the styling/color for the sent/received timestamp message ex: "2:26pm - Sent".

![image](https://user-images.githubusercontent.com/14806004/177414710-9e75a0c7-53e3-4e41-9914-1fa48f47ce8d.png)

**Comment by sarojkpr** [comment]
Please use 
`renderingMiddlewareProps: {
			timestampContentStyleProps:{
				color: "Yellow"
			},
			systemMessageStyleProps:{
				color: "Yellow"
			}
          }` inside `webChatContainerProps`
