### ISSUE TITLE
Footer icon color not updating on hover.

### ISSUE THREAD

**Issue by elishuwon-mitchell** [microsoft/omnichannel-chat-widget#66]
The color for the footer icons for downloadTranscript and audioNotification are not updating on hover when using the following props :
```
        "footerProps": {
            "controlProps": {
             ...
            },
            "styleProps": {
                ...
                "downloadTranscriptButtonHoverStyleProps": {
                    "backgroundColor": "#00FFFF",  //<-- This works
                    "color": "#F3F2F1", // <-- This does not work
                }
            }
        }         
```

The background color of the button updates appropriately but the color of the icon itself does not update to reflect the property set.

**Comment by sarojkpr** [comment]
This is fixed with latest version `0.1.0-main.7b290a7`
