### ISSUE TITLE
Audio Notification icon's color is not updating on hover

### ISSUE THREAD

**Issue by elishuwon-mitchell** [microsoft/omnichannel-chat-widget#68]
The color for the audioNotification icon is not updating on hover when using the following props:

        "footerProps": {
            "controlProps": {
             ...
            },
            "styleProps": {
                ...
                "audioNotificationButtonHoverStyleProps": {
                    "backgroundColor": "#00FFFF",  //<-- This works
                    "color": "#F3F2F1", // <-- This does not work
                }
            }
        }         

The previous release version fixed the issue for the downloadTranscript icon but the issue remains for the audioNotification icon.

**Comment by sarojkpr** [comment]
This issue has been fixed in `0.1.0-main.dbc1afa`
