### ISSUE TITLE
Widget needs to upgrade the botframework-webchat version to 4.15.0

### ISSUE THREAD

**Issue by dhruveshsheladiya** [microsoft/omnichannel-chat-widget#79]
We are getting component governance error with high-security vulnerability flagging from node-fetch v2.6.1. Here's the dependency chain:

![image](https://user-images.githubusercontent.com/10868253/181646277-fabcfaf8-902a-48c6-8373-566511218a62.png)

I can see the cross-fetch version is upgraded in the botframework-webchat v4.15.0. 

Please upgrade the botframework-webchat to 4.15.0.

**Comment by sarojkpr** [comment]
This has been fixed with latest version of component.
